declare type rsa_paddings = 'RSA_PKCS1_PADDING' |
'RSA_SSLV23_PADDING' |
'RSA_NO_PADDING' |
'RSA_PKCS1_OAEP_PADDING' |
'RSA_X931_PADDING' |
'RSA_PKCS1_PSS_PADDING' |
'RSA_PSS_SALTLEN_DIGEST' |
'RSA_PSS_SALTLEN_MAX_SIGN' |
'RSA_PSS_SALTLEN_AUTO'

export = rsa_paddings